;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Mon May 23 2022
; Processor: PIC16F84A
; Compiler:  MPASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

#include p16f84a.inc                ; Include register definition file

;====================================================================
; VARIABLES
STATE		EQU 0X30 ; STORE THE STATE OF FLASHING
COUNT1 	EQU 0X31 ; COUNTER FOR DELAY LOOP
COUNT2 	EQU 0X32 ; C
TEMP              EQU 0X33
SUSCOUNT   EQU 0X34

ORG 0X0000
GOTO START
ORG 0X0004
GOTO ISR


START CLRF 		STATE

BSF		 STATUS,RP0; SELECT BANK 1
MOVLW 		B'00000011' ; CONFIGURE RB0 and RB1 as INPUT
MOVWF 		TRISA
MOVLW 		B'00000001' 
MOVWF 		TRISB
BSF 	OPTION_REG, 	INTEDG ; SELECT RISING EDGE FOR EXTERNAL INTERRUPT
BSF 	INTCON , 	INTE ; ENABLE EXTERNAL INTERRUPT
BSF 	INTCON , 	GIE ; ENABLE GLOBAL INTERRUPT
BCF 	STATUS,	RP0 ; SELECT BANK 0
MOVLW 		B'00000010' ;
MOVWF  PORTB;
MOVLW D'15'
MOVWF  SUSCOUNT

SS
BSF		PORTB ,1;
CALL 	DEL_p5sec
BTFSS  STATE,0;
MOVLW 	B'00000010'
BTFSS  STATE,0;
MOVWF  PORTB;
BTFSS  STATE,0;
GOTO  SS

MOVLW 	B'00000010'
XORWF 	PORTB , F
CALL 	DEL_p5sec
MOVFW  PORTA
CALL TOTO
MOVWF  TEMP
SWAPF TEMP ,W
MOVWF  PORTB
;CALL SUS
GOTO  SS



ISR 		MOVLW   0x01
XORWF 	STATE, F ;COMPLEMENT THE STATUS
BCF 	INTCON , INTF ; CLEAR THE INTF FLAG
RETFIE


TOTO  addwf PCL,1
      retlw  D'3'
      retlw D'6'
      retlw D'9'
      retlw D'12'

SUS  MOVLW  0x20
  MOVWF  FSR
   SWAPF  PORTB ,W 
LOO  ADDWF  INDF,F
   INCF  FSR,F
   DECFSZ  SUSCOUNT
GOTO  LOO
MOVLW  0x20
 MOVWF  0x04
   RETURN

    
DEL_p5sec

MOVLW 	D'0'
MOVWF 	COUNT1
MOVLW 	D'44'
MOVWF 	COUNT2

LOOP 	NOP
NOP
NOP
NOP
NOP
DECFSZ 		COUNT1 , F
GOTO 	LOOP
DECFSZ 		COUNT2 , F
GOTO	 LOOP 
RETURN

END










 